BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[ComentCreatedDaily] (
    [id] INT NOT NULL IDENTITY(1,1),
    [to] NVARCHAR(1000) NOT NULL,
    [subject] NVARCHAR(1000) NOT NULL,
    [etitle] NVARCHAR(1000) NOT NULL,
    [eurl] NVARCHAR(1000) NOT NULL,
    [urllabel] NVARCHAR(1000) NOT NULL,
    [about] NVARCHAR(1000) NOT NULL,
    [aboutEnd] NVARCHAR(1000) NOT NULL,
    [unsubscribe] NVARCHAR(1000) NOT NULL,
    [created_at] DATETIME2 NOT NULL CONSTRAINT [ComentCreatedDaily_created_at_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [ComentCreatedDaily_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
