# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '9af6d245-59e5-4674-a474-0798335a4001'
  imageRepository: 'eurekastaging'
  containerRegistry: 'eurekastaging.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:


    # Job names can contain alphanumeric characters and '_', cannot start with a number
- stage: Tests
  displayName: Cypress Tests
  jobs:  
  - job: Cypress_e2e_tests
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'

      # NPM modules and Cypress binary should be cached
      # otherwise the install will be too slow
      # https://docs.microsoft.com/en-us/azure/devops/pipelines/caching/?view=azure-devops
      # since the username / user home directory are not available via system variables
      # (there is even an open question about it)
      # https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops
      # just use "/home/vsts" for now
      - task: CacheBeta@1
        inputs:
          key: yarn | $(Agent.OS) | yarn.lock
          path: /home/vsts/.yarn
          restoreKeys: yarn | $(Agent.OS) | yarn.lock
        displayName: Cache NPM packages
      - task: CacheBeta@1
        inputs:
          key: cypress | $(Agent.OS) | yarn.lock
          path: /home/vsts/.cache/Cypress
          restoreKeys: cypress | $(Agent.OS) | yarn.lock
        displayName: Cache Cypress binary

      - script: yarn install --frozen-lockfile
        displayName: 'Install NPM dependencies'

      - script: yarn cy:verify
        displayName: 'Cypress verify'

      - script: yarn test:ci
        displayName: 'Run Cypress tests'      