BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Action] ADD [cycleId] INT;

-- AddForeignKey
ALTER TABLE [dbo].[Action] ADD CONSTRAINT [Action_cycleId_fkey] FOREIGN KEY ([cycleId]) REFERENCES [dbo].[cycles]([id]) ON DELETE SET NULL ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
