export const WORK_ALREADY_EXIST="WORK_ALREADY_EXIST";
export const NOT_FOUND="NOT_FOUND";
export const EDITION_ALREADY_EXIST="EDITION_ALREADY_EXIST";
export const NOT_COVER_IMAGE_RECEIVED="NOT_COVER_IMAGE_RECEIVED";
export const SERVER_ERROR="SERVER_ERROR";
export const UNAUTHORIZED="UNAUTHORIZED";
export const MISSING_FIELD=(field:string)=>`MISSING_FIELD|${field}`;

 