export const DATE_FORMAT_HUMANIC_ADVANCED = 'MMMM Do YYYY';
export const DATE_FORMAT_PROPS = 'YYYY-MM-DD';
export const DATE_FORMAT_ONLY_YEAR = 'YYYY';
export const DATE_FORMAT_SHORT = 'D·MM·YYYY';
export const DATE_FORMAT_SHORT_MONTH_YEAR = 'MM/YYYY';

export const ASSETS_BASE_URL = process.env.NEXT_PUBLIC_LOCAL_ASSETS_BASE_URL;
export const CLARITY_TRACKING_ID = process.env.NEXT_PUBLIC_CLARITY_TRACKING_ID;
export const HYVOR_SSO_KEY = process.env.NEXT_PUBLIC_HYVOR_SSO_KEY;
export const HYVOR_WEBSITE_ID = process.env.NEXT_PUBLIC_HYVOR_WEBSITE_ID;
export const WEBAPP_URL = process.env.NEXT_PUBLIC_WEBAPP_URL;

export const LOCALE_COOKIE_NAME = 'NEXT_LOCALE';
export const LOCALE_COOKIE_TTL = 60 * 60 * 24 * 90;
